### PR TITLE
Code Beautifications

### PR DESCRIPTION
**Pull request by sethtroisi**
**Scope**: Code beautification, no op in behavior 
**known limitations:** None
**Testing plan:** Ran example .ino on my Arduino using this code of library

### CODE REVIEW

**Comment by ladyada** [comment]
hiya these look good, want to take a look at the remaining errors/complaints? looks like the esp32 compiler is warning on a lot :)

**Comment by sethtroisi** [comment]
When I first submitted this there were other warnings (that required changes I didn't have a plan to test (see https://github.com/adafruit/Adafruit_TSL2561/compare/master...sethtroisi:warnings)) but now it appears to be happy with these style changes.

**Comment by ladyada** [comment]
thanx!

**Comment by sethtroisi** [comment]
Thanks for letting me merge upstream in an older repo :)


IMG_20190403_145843

**Comment by ladyada** [comment]
wow, this is our first github thank you note! thanks for the commits :)

**Pull request merged**
